apiVersion: v1
kind: Service
metadata:
  name: scitec-lstm-service
spec:
  selector:
    app: scitec-lstm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Change if your app runs on a different port
  type: NodePort
